import { Ticket } from "@/types/ticket";
export const tickets: Ticket[] = [
    {
      id: "1",
      ticketid: "0001",
      adminreplying: "0",
      userid: "89",
      contactid: "177",
      email: "jane.smith@buildsoft.com",
      name: "Jane Smith",
      department: "IT Support",
      priority: "2",
      status: "1",
      service: "Technical Support",
      ticketkey: "abc123",
      subject: "A test ticket",
      message: "This is a test ticket message for demonstration purposes.",
      admin: "0",
      date: "2025-10-22 13:39:17",
      project_id: "0",
      lastreply: "0000-00-00 00:00:00",
      clientread: "1",
      adminread: "0",
      assigned: "0",
      line_manager: "0",
      milestone: "0",
    },
    {
      id: "2",
      ticketid: "0002",
      adminreplying: "1",
      userid: "89",
      contactid: "177",
      email: "john.doe@buildsoft.com",
      name: "John Doe",
      department: "IT Support",
      priority: "1",
      status: "2",
      service: "Technical Support",
      ticketkey: "def456",
      subject: "Network connectivity issue",
      message: "Unable to connect to the internal network.",
      admin: "0",
      date: "2025-10-21 10:15:00",
      project_id: "0",
      lastreply: "2025-10-21 14:30:00",
      clientread: "1",
      adminread: "1",
      assigned: "1",
      line_manager: "0",
      milestone: "0",
    },
  ];